name: exagonal
version: '9.8.9-FEB23'
summary: Exagonal is a simple bash app to understand bash principles.
description: "My App is a simple app that does literally nothing."
base: core18
confinement: strict

parts:
  my-app:
    source: .
    plugin: autotools
    build-packages:
      - python3
      - python3-pip
    stage-packages:
      - python3
      - python3-pip

apps:
  my-app:
    command: bin/exagonal
    desktop: usr/share/applications/exagonal.desktop
