name: xganolasmc
base: core22
version: '2.0.0'
summary: A bash native app for begginers.
description: |
  Simple bash app, for begginers, with no access to system ressources or whatever. It does nothing but show some info. It's for begginers to understand how bash works.
grade: stable
confinement: strict
apps:
  xganolasmc:
    command: bin/xganolasmc
    plugs: [home]

parts:
  yt-dlp:
    plugin: 
    source: 
